Test-More/test-more

t/Behavior/event_clone_args.t

typo in event_clone_args.t

---

.travis.yml
t/xxx-changes_updated.t

This test should not run under travis.

Fix Changes test under travis

---

lib/Test/More.pm

Hi, please review the above changes.
Many Thanks.
Best Regards,
Mohammad S Anwar

- Removed broken link to the package Bundle::Test

---

lib/Test/Builder.pm

$Level is accounted for in all contexts aquired after Test::Builder is
loaded.

Changes to go along with Test2 changes rjbs and I discussed

---

lib/Test2.pm
lib/Test2/API.pm
lib/Test2/API/Context.pm
lib/Test2/API/Instance.pm
lib/Test2/API/Stack.pm
lib/Test2/Event.pm
lib/Test2/Formatter.pm
lib/Test2/Formatter/TAP.pm
lib/Test2/Hub.pm
lib/Test2/IPC/Driver.pm
lib/Test2/IPC/Driver/Files.pm
lib/Test2/Transition.pod
lib/Test2/Util.pm
lib/Test2/Util/ExternalMeta.pm
lib/Test2/Util/HashBase.pm
lib/Test2/Util/Trace.pm

Noticed a few spelling mistakes and then couldn't stop myself. 😄 
Hopefully none of the changes are just differences between British English and American English.

Spelling fixes in Test2 POD

---

Changes
MANIFEST.SKIP
README
README.md
dist.ini
lib/Test/FAQ.pod
lib/Test/Tester.pm
lib/Test2/API.pm
lib/Test2/API/Context.pm
lib/Test2/API/Stack.pm
lib/Test2/Event.pm
lib/Test2/Formatter/TAP.pm
lib/Test2/Hub.pm
lib/Test2/IPC/Driver.pm
lib/Test2/Transition.pod
lib/Test2/Util/ExternalMeta.pm
lib/Test2/Util/HashBase.pm
t/Legacy/Tester/tbt_06errormess.t
t/Legacy/Tester/tbt_07args.t
xt/author/pod-spell.t

Also a small bug fixed involving `TESTTESTERCOLOR`.

spelling test and fixes

---

lib/Test2/IPC/Driver/Files.pm

Win32 can claim it finished writing/renaming/unlinking before actually
finishing, in which case it holds a lock. When there is a sequence of
such events the lock can trip us up, this will make it try a couple
times on win32.
I hope we can find a better way to do this in the future.

IPC: "Fix" win32 file operations

---

Changes
lib/Test2/API.pm
lib/Test2/Hub/Interceptor.pm
t/Test2/modules/Hub/Interceptor.t
t/lib/SkipAll.pm
t/regression/696-intercept_skip_all.t

Fix skip_all inside require inside intercept

---

Changes
lib/Test2.pm

Better documentation of what is better in Test2

---

Changes
lib/Test/Builder/Tester.pm

Document Test::Builder::Tester plan problems

---

Changes
lib/Test/More.pm

Document done_testing + END block problems

---

Changes
lib/Test2/API/Context.pm

Make ctx->send_event detect termination events

---

lib/Test/Builder.pm
lib/Test/Builder/Formatter.pm
lib/Test2/Event/Ok.pm
lib/Test2/Formatter/TAP.pm
t/Test2/behavior/special_names.t
t/Test2/legacy/TAP.t
t/Test2/modules/Event/Ok.t
t/Test2/modules/Formatter/TAP.t

Fixes #710
Formatter should handle escaping these, decouple from TAP!

Allow \n and # in Ok events

---

Changes
lib/Test/More.pm
t/Legacy/Regression/736_use_ok.t

Propogate warnings settings to use_ok

---

Changes
lib/Test2/API.pm
lib/Test2/Event.pm
lib/Test2/Util/Trace.pm
t/Test2/behavior/trace_signature.t
xt/author/pod-spell.t

- Add 'cid' to trace
- Add signature to trace
- Add related() to trace

Make it possible to check if events are related

---

lib/Test/Builder.pm
lib/Test2/API/Context.pm
lib/Test2/Formatter/TAP.pm

Fixes #751 
Doing a bunch of downstream testing, assuming it all goes well we can merge this.
I originally wrote this fix in the new event api branch, but realized it ports perfectly back to the master branch.

Move diag newline to TAP formatter

---

Changes
lib/Test2/API/Instance.pm
lib/Test2/Util.pm
t/Test2/modules/Util.t

Fixes #758
@xdg can you take a peek at this?

Fix issue localizing absent signal

---

lib/Test/Tutorial.pod

Hi Team,
Please review the PR.
Many Thanks,
Best Regards,
Mohammad S Anwar

- Fixed minor typo in the pod for Test::Tutorial.

---

lib/Test2/Util.pm

Remove duplicate export from Test2::Util

---

lib/Test2/API.pm

https://github.com/Test-More/test-more/commit/749fe4b170b831fee6bee4d9f3722fbb1dfb5ed8#diff-058b37166fbe3e828af5ad50bd5e6b9dR464

delete weak parameter

---

lib/Test/Tester.pm

Corrected a minor bug related to scope, resulting in excessive diagnostic test output

Fix to scope bug introduced in last PR

---

lib/Test/Builder/Module.pm

Point Test::Builder::Module users at documentation for how and why to replace it with Test2.

Refer to related documentation

---

Changes
lib/Test/FAQ.pod
lib/Test/More.pm
lib/Test/Tester.pm
lib/Test/Tester/Capture.pm

This involved replacing "it's" with "its" and other changes.
See https://duckduckgo.com/?q=english+grammar&ia=web ;
https://duckduckgo.com/?q=english+spelling&ia=web and for the lighter side:
* https://www.youtube.com/watch?v=8Gv0H-vPoDc
* https://shlomif.livejournal.com/53966.html
* http://i.imgur.com/HL1ZR.jpg .
=================
I hereby disclaim any implicit or explicit ownership of my changes in this
changeset, and put them under a multiple licence consisting of your choice of
one of more of:
- The CC0 / Public Domain - https://creativecommons.org/choose/zero/ .
- The MIT / Expat license - https://en.wikipedia.org/wiki/MIT_License
- The default licence of your project
- The https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License - version
2.1 or higher
- The …

Correct some broken grammar/spelling/syntax/etc.

---

t/Legacy/Builder/current_test.t
t/Legacy/buffer.t
t/Legacy/fail-like.t
t/Legacy/is_deeply_fail.t
t/Legacy/todo.t

Add strict/warnings to all unit tests

---

lib/Test2/IPC/Driver/Files.pm
lib/Test2/Util.pm

Remove unnnecesary load of POSIX in Test2::IPC::Driver::Files

Delay loading POSIX until it is needed

---

lib/Test/More.pm

Fix POD typo

---

examples/tools.t
lib/Test2/API.pm
lib/Test2/API/Breakage.pm
lib/Test2/API/InterceptResult.pm
lib/Test2/API/InterceptResult/Event.pm
lib/Test2/Event/Ok.pm
t/Legacy/Regression/683_thread_todo.t
t/Legacy/Regression/736_use_ok.t
t/Test2/behavior/subtest_bailout.t
t/Test2/modules/API/Breakage.t
t/Test2/modules/API/Instance.t
t/Test2/modules/API/InterceptResult.t
t/Test2/modules/API/InterceptResult/Squasher.t
t/Test2/modules/Hub/Interceptor.t
t/Test2/modules/Hub/Subtest.t
t/Test2/modules/IPC/Driver/Files.t
t/Test2/modules/Tools/Tiny.t
t/Test2/regression/gh_16.t

Corrected several spelling mistakes in several files.

Fix some minor misspelling

---

Changes
lib/Test/Builder.pm
lib/Test/Builder/Tester.pm
lib/Test2/API.pm
lib/Test2/API/InterceptResult/Event.pm
lib/Test2/AsyncSubtest.pm
lib/Test2/Compare.pm
lib/Test2/Event.pm
lib/Test2/Manual/Anatomy/EndToEnd.pm
lib/Test2/Manual/Anatomy/Event.pm
lib/Test2/Manual/Anatomy/Hubs.pm
lib/Test2/Manual/Anatomy/IPC.pm
lib/Test2/Manual/Testing/Todo.pm
lib/Test2/Manual/Tooling/Nesting.pm
lib/Test2/Manual/Tooling/Testing.pm
lib/Test2/Plugin.pm
lib/Test2/Suite.pm
lib/Test2/Tools.pm
xt/author/pod-spell.t

documentation fixes throughout for affect vs effect

---

Changes

- "over time" was duplicated
- markup for filename for clarity

Fix duplicated words in Changes
