Test-More/test-more

lib/Test/More/Tools.pm

If boolean.pm's -truth option is used, it modifies perl's internal truth
and false values.  In perl 5.20 with threads, this breaks strings inside
closures.  Thier values become corrupted or undef.  Avoid this issue by
pulling a string eval out of a closure and into a named sub.
Fixes #546

avoid stringification in a closure to work around issues with boolean.pm

---

t/zzz-check-breaks.t

...otherwise, prove fails in a fresh checkout.

skip zzz-check-breaks if no META.* file in place

---

lib/Test/Stream.pm
lib/Test/Stream/Event/Subtest.pm
lib/Test/Stream/Hub.pm
lib/Test/Stream/Subtest.pm
t/Test-Stream.t

Fix #579
subtest_tap really should be 2 options, one for buffering subtest
results, one for setting the subtest renderign spec.

Split subtest_tap into buffering and spec

---

lib/Test/Builder/Module.pm

According to the perldoc of 'base' pragma, it has now been recommended
towards the 'parent' pragma.
parent module's core module of 5.10 or later, but for people to write a new module now it is better that had been written on the document as use the parent module.

Changed pod about Test::Builder::Module.

---

MANIFEST.SKIP

Its inclusion in the shipped distribution is helpful for diagnosing how things
in the build came to be, without having to hunt down the git repository.

do not remove dist.ini from the build

---

dist.ini

0.01 - 0.04 of Test::Alien used Test::Stream, so you can get some events from both Test2 and Test::Alien which confuses things.

Breaks Test::Alien prior to 0.05

---

lib/Test/Builder.pm
lib/Test2/API/Instance.pm
lib/Test2/IPC.pm
t/Test2/modules/API/Instance.t

This makes it possible for preloading harnesses like forkprove and
Test2::Harness to preload Test::Builder.

Delay setting PID/TID

---

lib/Test/Builder.pm
lib/Test/Builder/Formatter.pm
lib/Test/Builder/Module.pm
lib/Test/Builder/Tester.pm
lib/Test/Builder/TodoDiag.pm
lib/Test/More.pm
lib/Test/Simple.pm
lib/Test2/API.pm
lib/Test2/API/Breakage.pm
lib/Test2/API/Instance.pm
lib/Test2/Event/Bail.pm
lib/Test2/Event/Diag.pm
lib/Test2/Event/Exception.pm
lib/Test2/Event/Note.pm
lib/Test2/Event/Ok.pm
lib/Test2/Event/Plan.pm
lib/Test2/Event/Skip.pm
lib/Test2/Event/Subtest.pm
lib/Test2/Event/Waiting.pm
lib/Test2/Formatter/TAP.pm
lib/Test2/Hub/Interceptor.pm
lib/Test2/Hub/Subtest.pm
lib/Test2/IPC.pm
lib/Test2/IPC/Driver/Files.pm
lib/Test2/Util.pm
lib/Test2/Util/ExternalMeta.pm
lib/Test2/Util/HashBase.pm

This is a number of micro-optimizations to the code.  These changes are not all well tested yet, but I'm opening this for discussion.
As a rough benchmark, I ran `perl -MTest::More -e'ok 1; done_testing;' 1000 times.  These changes reduced the runtime from 61.3 seconds to 55.9 seconds.
The largest gains are gotten by preventing unneeded modules from being loaded.  Lazy loading overload is trivial (and is what Test::Builder used to do).  Preventing `Config_heavy.pl` from being needed in most cases is also straightforward.
Preventing Exporter::Heavy from being needed is uglier.  In one case, a goto &Exporter::import is used rather than calling export_to_level.  I believe this may be problematic on older perl 5.8 releases.  In another case, it manually handles exporting $TODO, as …

Load time micro optimizations

---

lib/Test/Builder/Module.pm

On perl 5.8.4, modifying @_ and then using goto will cause segfaults
later in the program.  Exporter has an ExportLevel variable that we can
use to export to the correct location and avoid the goto.

use ExportLevel rather than goto when calling Exporter

---

lib/Test2/IPC/Driver/Files.pm
t/Test2/modules/IPC/Driver/Files.t

Explicitly concatenating paths with a forward slash doesn't work
so well on filesystems that don't use slashes as separators. So
use catfile instead.
Also, on VMS, all files have an extension and a zero-length
extension is returned as a '.' from readdir(), so only match
the start of the extension-less hub files when testing for them.

Filename portability for Test2.

---

lib/Test/More.pm

Extra arguments passed to "subtest" are just passed to the callback.
This is a very interesting feature as it allows to parametrice the
subtest that was already implemented but not documented.
This patch also deletes a useless line in the subtest subroutine.

subtest: document it passes extra arguments to the callback

---

dist.ini
lib/Test2/API/Breakage.pm
lib/Test2/Transition.pod

Declare breakage of Test::UseAllModules >= 0.12, <= 0.14 (#685)

---

lib/Test2/Formatter/TAP.pm

Test2::Util::HashBase just takes a plain list.
You won’t believe how I found this. :-)
I was running Porting/leakfinder.pl in the perl repository.  It executes every line in every file in a loop and checks whether the number of SVs goes up.  So it took this line from the documentation and reported it as a leak.
It was ‘leaking’ because it was creating constants with names like ARRAY(0X7F9C5982A698) (and one named ACCESSORS, too), so they wouldn’t overwrite the previous constants upon multiple ‘use Test2::Util::HashBase’ invocations.

Remove accessors=>[] in Test2::Formatter::TAP pod

---

lib/Test2/API/Context.pm

Fixed document.
change from 'Test2' to 'Test2::API'

fix doc in Test2::API::Context

---

lib/Test2/API.pm
t/Test2/modules/API.t

`` my $hub     = $params{hub}   || @$stack ? $stack->[-1] : $stack->top;``
is
``my $hub     = (  $params{hub}   || @$stack  ) ? $stack->[-1] : $stack->top;``
Probably it is correct below
`` my $hub     = $params{hub}   || (@$stack ? $stack->[-1] : $stack->top)``
By the way,  
``(@$stack ? $stack->[-1] : $stack->top)``  and ``$stack->top``  are the same effect.
Is this reason a performance?

fix failing contxt( hub => $hub )

---

t/00-report.t

Having both STDOUT and STDERR opened to the same scalar causes issues
on some 5.8.9 threaded builds.  Avoid this by opening them to null
output rather than a throwaway scalar.  This also means they are backed
by a real OS level filehandle rather than only working on the PerlIO
layer.

use null output rather than throwaway scalar to silence STDOUT/STDERR

---

lib/Test2/Formatter/TAP.pm
t/Test2/modules/Formatter/TAP.t

I closed #711, but one edge case was discussed after that.
Test::Harness would have problems with a test name ending with an
unescaped '\' character. This special cases that condition and escapes
it.

Fix edge case discussed in #711 (escape trailing slash)

---

lib/Test2.pm

Test::Suite (which doesn't exist on CPAN) was referenced in Test2.pm's POD.  This trivial change changes that to Test2::Suite.

Change reference from Test::Suite to Test2::Suite

---

lib/Test/Builder/Tester.pm
lib/Test/More.pm

- Test::More already has it's rt.cpan.org bug tracker disabled, so forward users directly here
- Test::Builder::Tester points to an active rt.cpan.org queue, but it points back to https://metacpan.org/release/Test-Builder-Tester, which is unexpected. Probably, it's better to disable it too?

Update bug tracker url in docs

---

lib/Test/Builder/Tester.pm
lib/Test/Tester.pm

This is a simple addition that activates color output on 'MSWin32' platforms.
No other code changes are needed.

add color support for 'MSWin32' platforms

---

lib/Test/More.pm
t/Legacy/is_deeply_fail.t

Previously this code would fail with the following message:
```
WHOA!  No type in _deep_check
This should never happen!  Please contact the author immediately!
```

Fix comparison of references to different VSTRING object

---

lib/Test2/Hub.pm
lib/Test2/IPC/Driver/Files.pm
lib/Test2/Util.pm
t/Test2/modules/IPC/Driver/Files.t

On windows, forked processes are threads, and reading from $$ gives the thread id instead, which is a negative number. This interferes with the field separator in filenames, so as a quick fix the - in the pid is replaced with a ~ and restored when reading the file.
The commit 8b929f15e3cb2b5ce36bc84010c06a68d69c9f3e should be backed out, as it would only serve to hide this kind of issue.

handle the minus on negative pids in forks on windows

---

t/Test2/modules/API/Context.t

The __LINE__ token is compiled as an op_const pointing to an SvPV containing
the stringification of the line number. But (caller)[2] yields an SvIV that
directly represents the line number.
The version of Data::Dumper in blead now uses its XS implementation by
default, even when its Deparse option is enabled; previously, Deparse forced
use of the pure-Perl implementation.
The XS and pure-Perl implementations of Data::Dumper differ slightly: the
pure-Perl implementation always dumps defined non-reference scalars with
quotes, while the XS implementation uses a quote-less representation for
small integers. (The precise differences have changed over time, however.)
Test-Simple/t/Test2/modules/API/Context.t uses the minimal testing library
in Test-Simple/t/tools.pl to test itself, and …

__LINE__ and (caller)[2] may be different under Data::Dumper

---

dist.ini

The [VersionFromModule] plugin no longer passes tests, and is no longer being
actively maintained -- but [RewriteVersion] can be used as a drop-in
replacement.
There are no differences in the build output; Test::Builder::IO::Scalar's
special fixed $VERSION is not affected because it is not declared with 'our'.

switch version provider plugins

---

Changes
lib/Test2/API.pm
t/Test2/regression/746-forking-subtest.t

This is an alternate fix for #746 
@rjbs

Add 'no_fork' option to run_subtest

---

lib/Test/Builder.pm
t/Legacy_And_Test2/diag_event_on_ok.t

`Test::Builder::ok` (`Test::Builder::_ok_debug`) sends two `Diag` events after a test failed when the name of test is defined. However `Test2::Tools::Tiny::ok` sends one `Diag` event. It's difficult to test with `intercept` and `fail_events` in a situation where these are mixed.
This p-r changes `Test::Builder::_ok_debug` to be combine messages into one `Diag` event.
```perl
use strict;
use warnings;
use Data::Dumper;
use Test2::API qw/intercept/;
use Test2::Tools::Tiny ();
use Test::More ();
$Data::Dumper::Indent   = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Useqq    = 1;
warn "# Test::More::ok\n";
warn Dumper(intercept { Test::More::ok(0, 'name') });
warn "# Test::Tools::Tiny::ok\n";
warn Dumper(intercept { Test2::Tools::Tiny::ok(0, 'name') });
```
<details> …

Combine messages into one diag event in Test::Builder::_ok_debug

---

lib/Test/Tester.pm
t/Legacy/check_tests.t

This PR implements handling in `check_test` for `diag`, so it is possible to pass a regular expression instead of a string for comparison.
```perl
check_test(
sub {
is_mystyle_qr("this", "that", "not mathing");
},
{
ok => 0, # expect this to fail
name => "not mathing",
diag => qr/Expected: 'this'\s+Got: 'that'/,
}
);
```
I have only implemented basic tests, please evaluate and get back to me if useful, needs improvements or discard it if useless...

Implementation of regexp handling in check_test for diag

---

lib/Test/Builder.pm
lib/Test2/API.pm
lib/Test2/API/Instance.pm
t/Legacy/subtest/callback.t
t/Test2/behavior/Subtest_callback.t
t/Test2/modules/API/Instance.t

as suggested in #800 
`Test2::API` now has pre-subtest callbacks.
I'm not sure that the way I wrote the `t/Legacy/subtest/callback.t` is the best way, I'm not clear on what I can and can not use.

add pre-subtest callbacks

---

lib/Test2/EventFacet/Hub.pm

In Debian we are currently applying the following patch to
Test-Simple.
We thought you might be interested in it too.
Description: add missing whatis entry
Origin: vendor
Author: gregor herrmann <gregoa@debian.org>
Last-Update: 2018-03-10
The patch is tracked in our Git repository at
https://salsa.debian.org/perl-team/modules/packages/libtest-simple-perl/raw/master/debian/patches/pod.patch
Thanks for considering,
gregor herrmann,
Debian Perl Group

add missing whatis entry

---

lib/Test2/Formatter.pm

Move the list of parameters of the finalize method to the appropriate place.

fixed Test2::Formatter's doc

---

lib/Test2/EventFacet/Parent.pm

The content of abstract is the same as Test2::EventFacet.
It is necessary to change to the contents of Test2::EventFacet::Parent.

fixed Test2::EventFacet::Parent's abstract

---

lib/Test2/API.pm

Sentences ending with a parenthetical phrase that ends
with an abbreviation such as 'etc.' still require a period
outside of the parentheses.
See https://english.stackexchange.com/a/23025/306017

API.pm: fix sentence ending in '(…etc.)' in POD

---

lib/Test2/Formatter/TAP.pm

Rather than checking if Term::Table can be loaded at compile time, wait
until table support is actually requested.  Term::Table will load a
number of extra modules, including Unicode::GCString.
Loading the extra modules slows down startup time, but can also lead to
changes in global destruction order.  If a test interacts with Test2
during global destruction, it is likely to cause warnings or errors due
to this.
While it may make sense to make adjustments to the behavior during
global destruction to be more robust, simply delaying loading of
Term::Table has speed benefits as well.
Fixes #837

delay checking for table support until requested

---

lib/Test2/Formatter/TAP.pm

There is code that is looking for the string 'TODO & skip', which was
based on the fact that on ASCII platforms any uppercase ASCII character
sorts by default to before every lowercase one.
This isn't true on EBCDIC platforms, so change the sort to explicitly
make T come before s
With this one line code change, Test2 passes all its tests on an EBCDIC z/OS system.  When I first tried things out there several months ago, a few more tests were failing, but those somehow went away in the interim.  This commit fixes the remaining failing tests.
There are other ways to fix this, but this seemed like the simplest for me to do, given that I'm not familiar with the nuances of the code as a whole.

Test2/Formatter/TAP.pm; Fix to work on EBCDIC systems

---

.travis.yml
t/HashBase.t

Lot of CPAN modules which are compatible with Perl 5.6.2 uses Test::More framework for their tests. Therefore it is still useful to have working Test::More on Perl 5.6.2. This pull request brings back support for Perl 5.6.2.

Fix support for Perl 5.6.2

---

lib/Test/Builder/Formatter.pm

noticed this error while using the TRIAL version 0.9990002 for Test2::Harness 
```
Use of uninitialized value in string eq at /usr/local/cpanel/3rdparty/perl/530/lib/perl5/cpanel_lib/Test/Builder/Formatter.pm line 44.
at /usr/local/cpanel/3rdparty/perl/530/lib/perl5/cpanel_lib/Test/Builder/Formatter.pm line 44.
Test::Builder::Formatter::info_tap(Test::Builder::Formatter=HASH(0x18c1b30), HASH(0x3ec1e30)) called at /usr/local/cpanel/3rdparty/perl/530/lib/perl5/cpanel_lib/Test2/Formatter/TAP.pm line 181
Test2::Formatter::TAP::event_tap(Test::Builder::Formatter=HASH(0x18c1b30), HASH(0x3ec1e30), 12) called at /usr/local/cpanel/3rdparty/perl/530/lib/perl5/cpanel_lib/Test2/Formatter/TAP.pm line 102
Test2::Formatter::TAP::write(Test::Builder::Formatter=HASH(0x18c1b30), …
```

Avoid to raise warnings from info / debug tap

---

lib/Test2/Transition.pod

`Test::Kit` has removed the breaking requirement and there is now a `Test::Aggregate` alternative that does not mess with any test framework internals.
I was a bit afraid to leave the `forkprove` recommendation alongside `yath`, it was never that great in the first place and it became even worse when we switched to Test2, while `yath` works always, hope that's not only my team's experience.

Updates to transition POD

---

t/Test2/modules/API/Breakage.t

Doing so can lead to a mismatch between %INC and the stash. This could
cause modules to get loaded twice.
In this case, Data::Dumper was being loaded by is_deeply and then loaded
again after %INC was de-localized. This led to lots of warnings once
Data::Dumper had warnings turned up.

Do not localize %INC in tests

---

lib/Test/Builder.pm
t/Legacy/Regression/is_capture.t

When comparing values using cmp_ok, a string eval is used to check using
the correct op. It also carries through the caller's warnings. If the
BEGIN inside the eval closes over a variable, it slightly alters how the
eval works. This leads to Devel::Cover tracking it like a sub, which
means it holds on to both the op tree, and the values it closes over.
That includes the values that are being compared. This means that
any references passed to Test::More::is would not be destroyed until
process end.
Avoid this by converting the warnings bits value to a string, and
inlining that in the generated code.

avoid closing over scalar in BEGIN block in cmp_ok eval

---

lib/Test2/IPC/Driver/Files.pm
t/Test2/modules/IPC/Driver/Files.t

Perl core may be adding trackable bool values.  This could impact the
output of Data::Dumper. Since we are comparing the output of
Data::Dumper in our internal is_deeply checks, make sure the values used
in some places are real bool values so their serialization will match.

use forced bool values for ready and complete in file rpc

---

t/Test2/modules/IPC/Driver/Files.t

File::Spec does not export, so the attempted import was being ignored.
catfile is being correctly used as a class method, so the import is not
needed.

remove invalid unused import from File::Spec

---

.github/workflows/macos.yml
.github/workflows/windows.yml

On 29th of April, git.io will stop redirecting.
The github workflows in this project use the git.io shortener. I've
changed those to use the original addresses to prevent the workflows
from starting failing.
Ref: https://github.blog/changelog/2022-04-25-git-io-deprecation/

Don't use git.io for cpm sources

---

.github/workflows/macos.yml
.github/workflows/windows.yml

When removing the use of the git.io redirector, the wrong replacement
URL was used. Correct the URL to point to the cpm script.
The add-path action has been removed. Switch to using the $GITHUB_PATH
file.

Windows and macOS CI fixes

---

lib/Test/Builder.pm
t/Legacy/cmp_ok.t
t/lib/MyOverload.pm

Fixes #896.
It isn't obvious what the `eq`, `!=`, or `length` checks are meant to accomplish. The existing tests don't demonstrate any purpose for them.

avoid failing when printing diagnostic info comparing partial overloaded objects

---

t/Legacy/Regression/870-experimental-warnings.t

The smartmatch operator (along with `given` and `when`) is being deprecated in Perl 5.38.
When the `experimental::smartmatch` does not exists anymore, that means a deprecation warning will be produced instead. Silence it.

Silence deprecation warning when testing smartmatch

---

Changes

isn't() was accidentally spelled "inst't()"
:-)

Changes - fixup typo

---

lib/Test/More.pm
t/Legacy/is_deeply_fail.t

VSTRING and LVALUE are possible return types from ref, but they are essentially special cases of SCALAR refs. As far as is_deeply is concerned, they should be treated as equivalent.
Update the _type function to normalize VSTRING and LVALUE into SCALAR, so that the deep checks properly treat them as equivalent.
This fixes errors from doing comparisons with LVALUE refs, as well as fixing VSTRINGs comparing equal to an equivalent normal SCALAR string.
Fixes #916

is_deeply: fix handling of VSTRING and LVALUE refs

---

lib/Test2/API/Instance.pm

avoid defined-or to fix compatibility with perl 5.8

---

lib/Test/Builder.pm

So far the test name was forced to be empty even when provided. Fix that to allow naming skipped tests this way:
Test::More->builder->skip('reason to skip', 'test description');
Without it is hard to find out which test was skipped from reading the generated TAP, especially when the skip reason is unspecific or used multiple times.

Test::Builder skip() uses provided test name

---

lib/Test2/API/Context.pm

`my $hub = $self->{+HUB};` not used in `sub diag`.

Remove an unused variable on Test2::API::Context

---

t/Test2/regression/gh_16.t

"require 5.20" checks for perl v5.200

fix perl version check in regression test

---

lib/Test2/Hub.pm

As far as I can tell, the intended logic is:
1. Build a set from passed-in arguments, represented as a hash.
2. Keep only context handlers that are not elements of the set (i.e. not keys of the hash).
However, what the code actually did was to compare the result of `!` (which is a boolean, numerically 0 or 1) to a coderef, which is always false. In other words, the remove_context_* methods would ignore their arguments and always remove everything.

Test2::Hub - fix remove_context_{aquire,init,release} logic

---

lib/Test2/API/InterceptResult.pm

Fixes a typo detected by the lintian tool on Debian

Fix typo in Test2/API/InterceptResult.pm

---

lib/Test2/API.pm
lib/Test2/API/Context.pm
lib/Test2/Tools/Exception.pm
lib/Test2/Tools/Warnings.pm
t/modules/Tools/Warnings.t

fixes #1004
This adds a system for queuing diag messages that will be attached to the next context that releases, upon release the diags will be issued so long as the context caused at least 1 failure. The diags will be disgarded if the context did not add any failures.
the `no_warnings` and `lives` tools both now automatically add the warning/exception to the diag queue.
Examples:
This will add the warning as a diagnostics message ok(no_warnings { warn "xxx" }, "Did not get any warnings");
This will not add the warning-diag as no failures are caused ok(!no_warnings { warn "xxx" }, "Got warnings");
This will add the exception as a diagnostics message ok(lives { die "XXX" }, "Did not die");
This will not add the exception as a diagnostics message ok(!lives { die "XXX" }, "Died");

Make it possible to queue up diag for the context

---

lib/Test2/Manual/Anatomy/IPC.pm

Update the link in Test2::Manual::Anatomy::IPC.
s/Test2::API::Driver::Files/Test2::IPC::Driver::Files/

Fix documentation bug on Test2::Manual::Anatomy::IPC

---

lib/Test2/API.pm
lib/Test2/Formatter/TAP.pm
lib/Test2/Tools/Tiny.pm
t/HashBase.t
t/Legacy/Regression/736_use_ok.t
t/Legacy/overload_threads.t
t/Legacy_And_Test2/preload_diag_note.t
t/Test2/behavior/init_croak.t
t/Test2/behavior/nested_context_exception.t
t/Test2/modules/API.t
t/Test2/modules/API/Breakage.t
t/Test2/modules/API/Instance.t
t/Test2/modules/Hub.t
t/Test2/modules/IPC/Driver.t
t/Test2/modules/IPC/Driver/Files.t
t/Test2/modules/Util.t
t/Test2/regression/ipc_files_abort_exit.t
t/modules/Require/Perl.t

The fix follows Zefram's suggestion from
https://www.nntp.perl.org/group/perl.perl5.porters/2012/05/msg186846.html
> On older perls, however, $] had a numeric value that was built up using
> floating-point arithmetic, such as 5+0.006+0.000002.  This would not
> necessarily match the conversion of the complete value from string form
> [perl #72210].  You can work around that by explicitly stringifying
> $] (which produces a correct string) and having *that* numify (to a
> correctly-converted floating point value) for comparison.  I cultivate
> the habit of always stringifying $] to work around this, regardless of
> the threshold where the bug was fixed.  So I'd write
>
>     use if "$]" >= 5.014, warnings => "non_unicode";
This ensures that the comparisons will still work when Perl's major …

fix string comparisons with $] to use numeric comparison instead

---

lib/Test/More.pm

`utf8` is the internal name for Perl's extended, lax UTF-8-like encoding, while `UTF-8` is the stricter standard form

Use the proper name for UTF-8 in documentation

---

t/regression/247_check_ref_bool.t

It's just a test file; we don't need a full dump of the user's `@INC`.

Simplify SKIP message when JSON::MaybeXS is not found

---

lib/Test/Builder.pm

When comparing values using Test::Builder::cmp_ok, a string eval is used to match the caller location, and to inject an arbitrary comparison op. When used with Devel::Cover, the string eval may close over any variables used in it, and maintain them for the lifetime of the program.
Instead of comparing the values directly in the string eval, generate an anonymous sub that will perform the comparison, and call it in a block eval.
This is a reoccurrance of a previous problem that was fixed with 4fe707c2dc3fe4e80767be33ce41a2a65d082574. Some combination of perl or module updates has brought back the issue. While there was a test included with the bug, it only fails when run with Devel::Cover, which isn't done during the automated or release testing.

avoid closing over values in string eval when comparing values

---

lib/Test2/IPC/Driver/Files.pm
lib/Test2/Util.pm
lib/Test2/Util/Sig.pm

POSIX is an extra module to load which many test scripts don't need themselves. Test2::Util was loading it for the try_sig_mask function, but this is only used in one place for the IPC mechanism. If the script isn't loading Test2::IPC or running with threads, it is not needed.
Move the try_sig_mask function to a separate module, and use the new module in Test2::IPC::Driver::Files. For backwards compatibility, maintain a try_sig_mask function in Test2::Util, but have it load and call the function in the new module. A new module is used rather than just delay loading POSIX, because for something involving threads or forks, loading at process start is preferrable.

move try_sig_mask to separate file to avoid always loading POSIX

---

lib/Test2/Util.pm

PerlIO::get_layers is always available if PerlIO is available, without needing to load PerlIO.pm. Rather than trying to load it, we can just test for the existence of the function.

use PerlIO::get_layers without loading PerlIO.pm

---

lib/Test2/Require/Threads.pm
lib/Test2/Util/Facets2Legacy.pm

Instead of base.pm, load the module and assign to @INC. This matches how the rest of the codebase sets a parent class.

don't use base

---

lib/Test2/API/Instance.pm
lib/Test2/Util.pm

CAN_SIGSYS is not used by Test2 anymore since the removal of the shm code in 4c1bdd27e7f7694cbdfe4ec83b79b1cf791b4bc5. It is however still used by Test2::Harness.
%Config has magic behavior where some values exist in Config.pm, and others need to load Config_heavy.pl. Checking the sig_name value will always force Config_heavy.pl to be loaded. Since CAN_SIGSYS is mostly not used, having it always force loading the heavy config provides a minor slowdown of loading Test::More. We can provide the function as a runtime check rather than a constant to avoid this.

calculate CAN_SIGSYS when called rather than as a constant

---

lib/Test/More.pm

I noticed a confusing line in `Test::More::use_ok()`. I think that the line has no use, even though I didn't test with Perl 5.6.0. 
See also http://www.perl-community.de/bat/poard/thread/21661.

Eliminate useless assignments of an empty list

---

lib/Test2/Tools/Warnings.pm
t/modules/Plugin/SRand.t
t/modules/Tools/ClassicCompare.t
t/modules/Tools/Warnings.t

This PR makes the functions of `Test2::Tools::Warnings` issue a warning when called in a void context, just like `Test2::Tools::Exception`.

Make `Test2::Tools::Warnings` warn when called in void context, like `Test2::Tools::Exception`

---

lib/Test2/Util/Trace.pm

I haven't added a Changes entry because the fix is so small. I can add one if you prefer to have one.

fix typo in Test2::Util::Trace docs

---

lib/Test2/Compare.pm

Seems like a reasonable thing to link to here

Test2::Compare: link to base class for Test2::Compare::*
